
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://192.168.0.81:3306/pdata?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: yangguo999

  redis:
    #数据库索引
    database: 0
    host: 192.168.0.81
    port: 6379

# 打印sql
logging:
  level:
    com.jifenkeji.pdata.mapper: DEBUG
    log4j.logger.com.ibatis: DEBUG
    log4j.logger.com.ibatis.common.jdbc.SimpleDataSource: DEBUG
    log4j.logger.com.ibatis.common.jdbc.ScriptRunner: DEBUG
    log4j.logger.com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate: DEBUG
    log4j.logger.Java.sql.Connection: DEBUG
    log4j.logger.java.sql.Statement: DEBUG
    log4j.logger.java.sql.PreparedStatement: DEBUG