spring:
  profiles: pub
  cache:
    type: redis
  redis:
    #数据库索引
    database: 0
    host: 192.168.0.81
    port: 6379
  datasource:
    url: jdbc:mysql://192.168.0.81:3306/pdata?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: yangguo999
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048