spring:
  profiles: dev


  datasource:
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:h2:mem:test
#    username: root
#    password: yangguo999

#  datasource:
    url: jdbc:mysql://192.168.0.81:3306/pdata?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: yangguo999


  redis:
    #数据库索引
   database: 0
   host: 192.168.0.81
   port: 7000

  thymeleaf:
    #前缀，也就是模板存放的路径
    #prefix=classpath:/web/
    #编码格式
    encoding: UTF-8
    #是否开启缓存
    cache: false
    #后缀
    suffix: .html
    #设置不严格的html
    mode: LEGACYHTML5


# 打印sql
logging:
  level:
    com.jifenkeji.pdata: DEBUG
    log4j.logger.com.ibatis: DEBUG
    log4j.logger.com.ibatis.common.jdbc.SimpleDataSource: DEBUG
    log4j.logger.com.ibatis.common.jdbc.ScriptRunner: DEBUG
    log4j.logger.com.ibatis.sqlmap.engine.impl.SqlMapClientDelegate: DEBUG
    log4j.logger.Java.sql.Connection: DEBUG
    log4j.logger.java.sql.Statement: DEBUG
    log4j.logger.java.sql.PreparedStatement: DEBUG

